name: 'James Neate'
description: 'Use this GitHub Action to push Collection(s) from GitHub into a specific Postman Workspace'
author: 'jneate'
inputs:
  postmanApiKey:
    required: true
    description: 'The API Key used for the Postman Workspace'
  postmanWorkspaceId:
    required: false
    description: 'The ID for the Postman Workspace - Defaults to <My Workspace>'
  postmanTimeout:
    required: false
    description: 'The number of milliseconds to wait for Postman APIs to respond before timing out - Defaults to 15000'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'orange'